fix yaml2

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -18,14 +18,14 @@ script:
   - if [ -n "$(gofmt -l .)" ]; then echo "Please fix source formatting by 'go fmt ./...'"; false; fi
   # Verify for  .c/.h formatting issues
   - >
-    CLANG_FORMAT_CMD=( git-clang-format --style="{BasedOnStyle: Google, IndentWidth: 2}" --extensions=c,cpp,h )
-    "${CLANG_FORMAT_CMD[@]}" --diff | egrep "^no modified files to format$" &> /dev/null
-    if [ $? -ne 0 ]; then
-      "${CLANG_FORMAT_CMD[@]}" --diff
-      echo -e "\n\nclang-format failed. Please apt-get install clang-format and format source by:\n"
-      printf '%q ' "${CLANG_FORMAT_CMD[@]}"
-      echo -e "HEAD~\n"
-      exit 1
+    CLANG_FORMAT_CMD=( git-clang-format --style="{BasedOnStyle: Google, IndentWidth: 2}" --extensions=c,cpp,h );
+    "${CLANG_FORMAT_CMD[@]}" --diff | egrep "^no modified files to format$" &> /dev/null;
+    if [ $? -ne 0 ]; then;
+      "${CLANG_FORMAT_CMD[@]}" --diff;
+      echo -e "\n\nclang-format failed. Please apt-get install clang-format and format source by:\n";
+      printf '%q ' "${CLANG_FORMAT_CMD[@]}";
+      echo -e "HEAD~\n";
+      exit 1;
     fi
   # Run unit tests
   - go test -v -coverprofile=coverage.txt -covermode=atomic
